<template>
    <div style="margin-left: 7%; margin-top: 2%">
        <a-typograhy style="font-size: 20px" rows="2">
            <a-typography-text strong>Observations on Spectrum Reflectance</a-typography-text>
            <a-typography-paragraph
                    :ellipsis="ellipsis ? { rows: 2, expandable: true, symbol: 'more', onExpand: expand } : false"
                    style="white-space: pre-line;"
                    content="1.In urban and vegetation areas, the reflectance of near-infrared is greater than that of three visible channels. 2.In the
                     sky, clouds and water areas, the reflectance of near-infrared is weaker than that of three visible channels. 3.The reflec-
                     tance of near-infrared spectrum is generally high, and usually exhibit lower dynamic range but high bright."
            ></a-typography-paragraph>
            <div v-if="show">
                <a-typography-text strong>Observations on Spectrum Transmittance</a-typography-text>
                <a-typography-paragraph
                        style="white-space: pre-line;"
                        content="1.Areas with fog in near-infrared reflection components have more fine details. 2.The details are on the decrease as t-
                        he wavelength of spectrum becomes shorter."
                />
                <a-typography-text strong>The Reflection Weight Model</a-typography-text>
                <a-typography-paragraph
                        style="white-space: pre-line;"
                        content="1.The reflection weight model based on the observations of the difference in the reflection component of visible cha-
                        nnels and near-infrared channel. 2.The reflection weight model can be calculate by (nir-rgb) / (nir+rgb), and then no-
                        rmalize."
                />
                <a-typography-text strong>The Transmission Weight Model</a-typography-text>
                <a-typography-paragraph
                        style="white-space: pre-line;"
                        content="1.Get the base layers. The base layers from the guided filter are the input images of the Gaussian low-pass filter. 2.G-
                        et the detail layers. After the base layers being generated, the detail layers are calculated as ratio. 3.Get the gradient
                        maps. The gradient maps can be generated by the detail layers. 4.Transmission weight model. The ratio of gradient
                        maps of visible channels to near-infrared are used to approximate transmission of visible channels. And then, the gu-
                        ided filter is applied to smooth the block."
                />
                <a-typography-text strong>Fusion Result</a-typography-text>
                <a-typography-paragraph
                        style="white-space: pre-line;"
                        content="1. Init fusion. Multiply the reflection weight and transmission weight as final fusion weight of visible detail layer. Com-
                        bining the fused detail layer and the correspondent base layer. 2.Non-Uniform Illumination Enhancement. Apply the
                        same way of reflection weight model to the lightness and enhance the low light part of the image."
                />
            </div>
        </a-typograhy>
    </div>
</template>

<script>
    import { defineComponent, ref } from 'vue';
    export default defineComponent({
        data() {
            return {
                show: false
            }
        },
        setup() {
            return {
                ellipsis: ref(true),
            };
        },
        methods: {
            expand(event) {
                console.log(event)
                this.show = true;
            }
        }
    })
</script>

<style scoped>

</style>